language: java
jdk:
- oraclejdk7
notifications:
  slack:
    secure: UcdDkvMAJR0bPKgGGItUP+VUNesM7EnUG4KgTm7MG/8Y+VqO9HLLrtZDPhbwIeFn9Ji0ZfkOCQUDdoh1ZhdwIl2fQLpQ9YbdcL/bPkTvYtvMJ1LhxZiEKeA6Kkg9HCWxYAp4+9+nnr8S8VZGauyd+A2OjQ+5kH6bpBoZPT90hgk=
after_success:
- mvn jacoco:report coveralls:jacoco
